### ISSUE TITLE
Part 4: Storing data into Postgres database

### ISSUE THREAD

**Issue by tomkoos** [tomkoos/SI507F17_finalproject#5]
files: database.py, config.py
- [x] Create a database table for a list of world heavyweight boxing champions
- [x] Create a database table for list of countries
- [x] For each boxer, create a table that store the boxing records

**Comment by aerenchyma** [comment]
This sounds like a really interesting project, I'm glad you found some unusual and exciting data to play around with here.

You may want to consider whether or not you need a table for the timeline -- is the reign start - end maybe a field of the individual boxer themselves?

**Comment by tomkoos** [comment]
You're right. I decided to put the reign days inside the main list of champions instead of creating a whole new table.
